src/Entity/Badge.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BadgeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=BadgeRepository::class)
 * @ORM\Table(name="`badge`")
 * @UniqueEntity(fields={"name"}, message="Cette valeur est déjà utilisée.")
 * @Vich\Uploadable()
 */
class Badge
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected string $name;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $description;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/jpg", "image/png"}
     * )
     * @Vich\UploadableField(mapping="badge_image", fileNameProperty="url_image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected ?string $url_image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected string $action_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected string $action_delimiter;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected string $action_quantity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected string $role_delimiter;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $badge_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $badge_modified_at;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Badge
     */
    public function setName(string $name): Badge
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Badge
     */
    public function setImageFile(?File $imageFile): Badge
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->badge_modified_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    /**
     * @param string|null $url_image
     * @return Badge
     */
    public function setUrlImage(?string $url_image): Badge
    {
        $this->url_image = $url_image;
        return $this;
    }

    /**
     * @return string
     */
    public function getActionName(): string
    {
        return $this->action_name;
    }

    /**
     * @param string $action_name
     * @return Badge
     */
    public function setActionName(string $action_name): Badge
    {
        $this->action_name = $action_name;
        return $this;
    }

    /**
     * @return string
     */
    public function getActionDelimiter(): string
    {
        return $this->action_delimiter;
    }

    /**
     * @param string $action_delimiter
     * @return Badge
     */
    public function setActionDelimiter(string $action_delimiter): Badge
    {
        $this->action_delimiter = $action_delimiter;
        return $this;
    }


    public function getActionQuantity(): string
    {
        return $this->action_quantity;
    }

    public function setActionQuantity(string $action_quantity): Badge
    {
        $this->action_quantity = $action_quantity;
        return $this;
    }

    /**
     * @return string
     */
    public function getRoleDelimiter(): string
    {
        return $this->role_delimiter;
    }

    /**
     * @param string $role_delimiter
     * @return Badge
     */
    public function setRoleDelimiter(string $role_delimiter): Badge
    {
        $this->role_delimiter = $role_delimiter;
        return $this;
    }

    public function getBadgeCreatedAt(): ?\DateTimeInterface
    {
        return $this->badge_created_at;
    }

    public function setBadgeCreatedAt(\DateTimeInterface $badge_created_at): self
    {
        $this->badge_created_at = $badge_created_at;

        return $this;
    }

    public function getBadgeModifiedAt(): ?\DateTimeInterface
    {
        return $this->badge_modified_at;
    }

    public function setBadgeModifiedAt(?\DateTimeInterface $badge_modified_at): self
    {
        $this->badge_modified_at = $badge_modified_at;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getUrlImage();
    }
}

src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{
    protected ManagerRegistry $managerRegistry;

    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry;
    }

    /**
     * @Route ("/", name="home")
     * @throws \Exception
     */
    public function home(): Response
    {
        $news = $this->managerRegistry
            ->getRepository(Post::class)
            ->findLatestWithLimit(3);

        return $this->render('site/home.html.twig', [
            'news' => $news,
        ]);
    }
}

templates/site/home.html.twig
{%  extends 'site/partials/base.html.twig' %}

{% block title %}Accueil - Front2Back{% endblock %}

{% block body %}

    <section class="presentation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Bienvenue sur Front2Back</h1>
                    <p>
                        Front2Back est un site de gestion de projet de développement web.
                        Vous pouvez y créer vos projets, les gérer, les partager, les commenter, les liker, les suivre, etc.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="news container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2>Les dernières news</h2>
            </div>
        </div>
        {% for new in news %}
            <div class="row mt-5 mb-5 horizontal-card">
                <div class="col-sm-12 col-md-4 card-image">
                    {% if new.urlImage is not null %}
                        <img src="{{ vich_uploader_asset(new, 'imageFile')}}" alt="image de la veille">
                    {% else %}
                        Cet article n'a pas encore d'image
                    {% endif %}
                </div>
                <div class="col-sm-12 col-md-8 card-content">
                    <h3>{{ new.title }}</h3>
                    <p>
                        {{ new.excerpt }}
                    </p>
                    <a class="btn btn-primary" href="{{ path('veilles_show', {'slug': new.slug}) }}">Lire la suite</a>
                </div>
            </div>
        {% endfor %}
    </section>

{% endblock %}

templates/site/register.html.twig
{%  extends 'site/partials/base.html.twig' %}

{% block title %}Inscription - Front2Back{% endblock %}

{% block body %}

    <h1>S'inscrire</h1>

    <div class="container">
        {{ form_start(form) }}
        <div class="row">
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_row(form.firstname) }}
            </div>
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_row(form.email) }}
            </div>
            <div class="col-12 mb-3">
                {{ form_row(form.password) }}
            </div>

            <button type="submit" class="btn btn-primary">S'inscrire</button>

            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}