src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Class Post.
 *
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une autre veille posséde déjà ce titre, merci de le modifier"
 * )
 * @UniqueEntity(
 *     fields={"slug"},
 *     message="Ce slug est déjà utilisé pour une autre veille."
 * )
 * @Vich\Uploadable()
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected ?int $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected ?string $title;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected ?string $slug;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/jpg", "image/png"}
     * )
     * @Vich\UploadableField(mapping="post_image", fileNameProperty="url_image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected ?string $url_image;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $excerpt;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $content;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $ref_description;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $post_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $post_modified_at;

    /**
     * @ORM\Column(type="boolean")
     */
    protected bool $validatedAt;

    /**
     * @ORM\Column(type="integer")
     */
    protected int $viewsCount = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     */
    protected ?User $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="post")
     */
    private $favorites;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="posts")
     */
    protected Collection $tag;

    public function __construct()
    {
        $this->tag = new ArrayCollection();
    }

    //getters and setters
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->updatedAt = new \DateTime('now');
        }

//        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(?string $urlImage): self
    {
        $this->url_image = $urlImage;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->excerpt;
    }

    public function setExcerpt(string $excerpt): self
    {
        $this->excerpt = $excerpt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getRefDescription(): ?string
    {
        return $this->ref_description;
    }

    public function setRefDescription(string $ref_description): self
    {
        $this->ref_description = $ref_description;

        return $this;
    }

    public function getPostCreatedAt(): ?\DateTimeInterface
    {
        return $this->post_created_at;
    }

    public function setPostCreatedAt(\DateTimeInterface $post_created_at): self
    {
        $this->post_created_at = $post_created_at;

        return $this;
    }

    public function getPostModifiedAt(): ?\DateTimeInterface
    {
        return $this->post_modified_at;
    }

    public function setPostModifiedAt(?\DateTimeInterface $post_modified_at): self
    {
        $this->post_modified_at = $post_modified_at;

        return $this;
    }

    public function isValidatedAt(): ?bool
    {
        return $this->validatedAt;
    }

    public function setValidatedAt(bool $validatedAt): self
    {
        $this->validatedAt = $validatedAt;

        return $this;
    }

    public function getViewsCount(): ?int
    {
        return $this->viewsCount;
    }

    public function setViewsCount(int $viewsCount): self
    {
        $this->viewsCount = $viewsCount;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $user): self
    {
        $this->author = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): Comment
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): Post
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setPost($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): Post
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getPost() === $this) {
                $favorite->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
            $tag->addPost($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
            $tag->removePost($this);
        }

        return $this;
    }

//    public function getTag(): ?Tag
//    {
//        return $this->tag;
//    }
//
//    public function setTag(?Tag $tag): self
//    {
//        $this->tag = $tag;
//
//        return $this;
//    }

//    public function getUser(): ?User
//    {
//        return $this->user;
//    }
//
//    public function setUser(?User $user): self
//    {
//        $this->user = $user;
//
//        // set (or unset) the owning side of the relation if necessary
//        $newAvatar = null === $user ? null : $this;
//        if ($user->getAvatar() !== $newAvatar) {
//            $user->setAvatar($newAvatar);
//        }
//
//        return $this;
//    }

    public function __toString()
    {
        return (string) $this->getUrlImage();
    }

    /**
     * To initialize slug on persist or update.
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(): void
    {
        $slugify = new Slugify();
        $this->slug = $slugify->slugify($this->title);
//        if(empty($this->slug)){
//            $slugify = new Slugify();
//            $this->slug = $slugify->slugify($this->title);
//        }
//        if(!empty($this->slug)){
//            $slugify = new Slugify();
//            $this->slug = $slugify->slugify($this->title);
//        }
    }
}

src/Controller/Admin/ContributorsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PostController.
 *
 * @Route ("/admin/contributors")
 */
class ContributorsController extends AbstractController
{
    private ManagerRegistry $doctrine;
    private RequestStack $request;

    public function __construct(ManagerRegistry $managerRegistry, RequestStack $request)
    {
        $this->doctrine = $managerRegistry;
        $this->request = $request;
    }

    /**
     * @Route ("/", name="admin_contributors_index")
     */
    public function index(PaginatorInterface $paginator): Response
    {
        //pour être contributeur, il faut faire la demande d'adhésion via le formulaire
        //ensuite l'administrateur doit valider la demande
        //dump($this->doctrine->getRepository(User::class)->findUserWithRequests());
//        dump($this->doctrine->getRepository(User::class)->findUserByRequestContributingOnRequesting('contributor'));
        //die();
        $contributors = [];
        $usersWithRequests = $this->doctrine->getRepository(User::class)->findUserWithRequests();
        foreach ($usersWithRequests as $user) {
            if (!empty($user->getRequests()) && $user->getRequests()['contributor'] !== null) {
                $contributors[] = $user;
            }
        }
        $paginateContributors = $paginator->paginate(
            $contributors,
            $this->request->getCurrentRequest()->query->getInt('page', 1),
            10
        );

        //change function to get contributors
        //$contributors = $this->doctrine->getRepository(User::class)->findAll();

        return $this->render('admin/contributors/index.html.twig', [
            'contributors' => $paginateContributors,
        ]);
    }

    /**
     * @param $id
     * @param User $user
     * @return Response
     * @Route ("/{id}/accept", name="admin_accept_new_contributor")
     */
    public function validateUserContributingRequest($id, User $user): Response
    {
        //change function to get contributors
        $userWhoRequestForContributing = $this->doctrine->getRepository(User::class)->findBy(['id' => $id])[0];

        //change requesting array to done
        $requestsForContributing = $userWhoRequestForContributing->getRequests();
        $requestsForContributing['contributor'] = "Cet utilisateur contribue depuis le ". date('d/m/Y');
        $userWhoRequestForContributing->setRequests($requestsForContributing);
        $userWhoRequestForContributing->setRoles(['ROLE_CONTRIBUTOR']);
        $this->doctrine->getManager()->flush();

        $this->addFlash(
            'success',
            "La contribution de <strong>{$userWhoRequestForContributing->getFirstname()}</strong>
                    a bien été prise en compte !"
        );

        return $this->redirectToRoute('admin_contributors_index');
    }

    /**
     * @param $id
     * @param User $user
     * @return Response
     * @Route ("/{id}/decline", name="admin_decline_new_contributor")
     */
    public function declineUserContributingRequest($id, User $user): Response
    {
        //change function to get contributors
        $userWhoRequestForContributing = $this->doctrine->getRepository(User::class)->findBy(['id' => $id])[0];

        //change requesting array to done
        $requestsForContributing = $userWhoRequestForContributing->getRequests();
        $requestsForContributing['contributor'] = "Cet utilisateur a arrêté de contribuer depuis le ". date('d/m/Y');
        $userWhoRequestForContributing->setRequests($requestsForContributing);
        $userWhoRequestForContributing->setRoles(['ROLE_USER']);
        $this->doctrine->getManager()->flush();

        $this->addFlash(
            'success',
            "La contribution de <strong>{$userWhoRequestForContributing->getFirstname()}</strong> a bien été suprimée !"
        );

        return $this->redirectToRoute('admin_contributors_index');
    }
}

src/Controller/Admin/PostController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use App\Entity\User;
use App\Form\Posts\PostType;
use App\Repository\PostRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PostController.
 *
 * @Route ("/admin/veilles")
 */
class PostController extends AbstractController
{
    private ManagerRegistry $doctrine;
    private RequestStack $request;

    public function __construct(ManagerRegistry $managerRegistry, RequestStack $request)
    {
        $this->doctrine = $managerRegistry;
        $this->request = $request;
    }

    /**
     * @Route ("/dashboard", name="admin_posts_dashboard")
     *
     * @throws \Exception
     */
    public function dashboard(PaginatorInterface $paginator, PostRepository $postRepository): Response
    {
        $posts = $paginator->paginate(
            $postRepository->findAllRecent(),
            $this->request->getCurrentRequest()->query->getInt('page', 1),
            10
        );

        return $this->render('admin/posts/dashboard.html.twig', [
            'posts' => $posts,
        ]);
    }

    /**
     * @Route ("/create", name="admin_posts_create")
     */
    public function create(): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post)->handleRequest($this->request->getCurrentRequest());

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $user = $this->getUser();

            $post->setPostCreatedAt(new \DateTime('now'));
            $post->setAuthor($user);
            $post->setValidatedAt(true);
            $this->doctrine->getManager()->persist($post);
            $this->doctrine->getManager()->flush();

            $this->addFlash(
                'success',
                "L'article <strong>{$post->getTitle()}</strong> a bien été crée !"
            );

            return $this->redirectToRoute('admin_posts_dashboard');
        }

        return $this->render('admin/posts/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route ("/edit/{slug}", name="admin_posts_edit")
     */
    public function edit(Post $post): Response
    {
        $form = $this->createForm(PostType::class, $post)->handleRequest($this->request->getCurrentRequest());

        if ($form->isSubmitted() && $form->isValid()) {
            /* @var User $user */
            //$user = $this->getUser();

            //$post->setPostCreatedAt(new \DateTime('now'));
            $post->setPostModifiedAt(new \DateTime('now'));
            //$post->setAuthor($user);
            $post->setValidatedAt(true);
            $this->doctrine->getManager()->flush();

            $this->addFlash(
                'success',
                "L'article <strong>{$post->getTitle()}</strong> a bien été mis à jour !"
            );

            return $this->redirectToRoute('admin_posts_dashboard');
        }

        return $this->render('admin/posts/edit.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);
    }

    /**
     * @Route ("/delete/{slug}", name="admin_posts_delete")
     */
    public function delete(Post $post): Response
    {
        $this->doctrine->getManager()->remove($post);
        $this->doctrine->getManager()->flush();

        $this->addFlash(
            'success',
            "La veille <strong>{$post->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute('admin_posts_dashboard');
    }
}

templates/contributor/posts/create.html.twig
{% extends 'contributor/partials/base.html.twig' %}

{% block title %}Créer votre nouvelle veille{% endblock %}

{% block body %}
    <div class="container frame mb-3">
        <h1>Créer votre nouvelle veille</h1>
    </div>
    <div class="container frame">
        {{ form_start(form) }}
        <div class="row">
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_errors(form.title) }}
                {{ form_label(form.title) }}
                {{ form_widget(form.title) }}
            </div>
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_errors(form.slug) }}
                {{ form_label(form.slug) }}
                {{ form_widget(form.slug) }}
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                {{ form_errors(form.imageFile) }}
                {{ form_label(form.imageFile) }}
                {{ form_widget(form.imageFile) }}
            </div>
            <div class="col-12 mb-3">
                {{ form_errors(form.refDescription) }}
                {{ form_label(form.refDescription) }}
                {{ form_widget(form.refDescription) }}
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                {{ form_errors(form.excerpt) }}
                {{ form_label(form.excerpt) }}
                {{ form_widget(form.excerpt) }}
            </div>
            <div class="col-12 mb-3">
                {{ form_errors(form.content) }}
                {{ form_label(form.content) }}
                {{ form_widget(form.content) }}
            </div>
        </div>
        <div class="row">
            <button class="btn btn-primary" type="submit">Créer la veille</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/contributor/posts/dashboard.html.twig
{% extends 'contributor/partials/base.html.twig' %}

{% block title %}Gestion des veilles {% endblock %}

{% block body %}
    <div class="container frame">
        <div class="row">
            <div class="col-md-12 col-lg-9">
                <h1>Vos dernières veilles </h1>
            </div>
            <div class="col-md-12 col-lg-3 cta-align">
                <a href="{{ path('contributor_posts_create') }}" class="btn btn-primary">Créer une nouvelle veille</a>
            </div>
        </div>
    </div>
    <div class="container frame mt-5">
        <div class="row">
            <div class="col-12">
                <table class="table table-borderless table-responsive">
                    <thead>
                        <tr class="table-light">
                            <th>Image</th>
                            <th>Titre</th>
                            <th>Extrait</th>
                            <th>Créé le</th>
                            <th>Modifié le</th>
                            <th>Editer</th>
                            <th>Supprimer</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if posts.items|length > 0 %}
                        {% for post in posts %}
                            <tr>
                                <td>
                                    {% if post.urlImage is not null %}
                                        <img class="img-fluid" src="{{ vich_uploader_asset(post, 'imageFile')}}" alt="image de la veille" width="150px" height="150px">
                                    {% else %}
                                        Cet article n'a pas encore d'image
                                    {% endif %}
                                </td>
                                <td>
                                    {{ post.title }}
                                </td>
                                <td>
                                    {{ post.excerpt }}
                                </td>
                                <td>
                                    {{ post.postCreatedAt | date("d/m/Y H:i:s") }}
                                </td>
                                <td>
                                    {% if post.postModifiedAt is not null %}
                                        {{ post.postModifiedAt | date("d/m/Y H:i:s") }}
                                    {% else %}
                                        Cette veille n'a pas encore été modifiée
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ path('contributor_posts_edit', {'slug': post.slug}) }}" class="btn btn-success">
                                        <svg height="32px" viewBox="0 0 512 511" width="32px" xmlns="http://www.w3.org/2000/svg">
                                            <path d="m405.332031 256.484375c-11.796875 0-21.332031 9.558594-21.332031 21.332031v170.667969c0 11.753906-9.558594 21.332031-21.332031 21.332031h-298.667969c-11.777344 0-21.332031-9.578125-21.332031-21.332031v-298.667969c0-11.753906 9.554687-21.332031 21.332031-21.332031h170.667969c11.796875 0 21.332031-9.558594 21.332031-21.332031 0-11.777344-9.535156-21.335938-21.332031-21.335938h-170.667969c-35.285156 0-64 28.714844-64 64v298.667969c0 35.285156 28.714844 64 64 64h298.667969c35.285156 0 64-28.714844 64-64v-170.667969c0-11.796875-9.539063-21.332031-21.335938-21.332031zm0 0"/><path d="m200.019531 237.050781c-1.492187 1.492188-2.496093 3.390625-2.921875 5.4375l-15.082031 75.4375c-.703125 3.496094.40625 7.101563 2.921875 9.640625 2.027344 2.027344 4.757812 3.113282 7.554688 3.113282.679687 0 1.386718-.0625 2.089843-.210938l75.414063-15.082031c2.089844-.429688 3.988281-1.429688 5.460937-2.925781l168.789063-168.789063-75.414063-75.410156zm0 0"/><path d="m496.382812 16.101562c-20.796874-20.800781-54.632812-20.800781-75.414062 0l-29.523438 29.523438 75.414063 75.414062 29.523437-29.527343c10.070313-10.046875 15.617188-23.445313 15.617188-37.695313s-5.546875-27.648437-15.617188-37.714844zm0 0"/>
                                        </svg>
                                    </a>
                                </td>
                                <td>
                                    <form action="{{ path('contributor_posts_delete', {'slug': post.slug}) }}" onsubmit="return confirm('Etes-vous sûr de supprimer cet article ?')">
                                        <button class="btn btn-danger">
                                            <svg id="Layer_1" enable-background="new 0 0 512 512" height="32" viewBox="0 0 512 512" width="32" xmlns="http://www.w3.org/2000/svg">
                                                <g>
                                                    <path d="m424 64h-88v-16c0-26.51-21.49-48-48-48h-64c-26.51 0-48 21.49-48 48v16h-88c-22.091 0-40 17.909-40 40v32c0 8.837 7.163 16 16 16h384c8.837 0 16-7.163 16-16v-32c0-22.091-17.909-40-40-40zm-216-16c0-8.82 7.18-16 16-16h64c8.82 0 16 7.18 16 16v16h-96z"/>
                                                    <path d="m78.364 184c-2.855 0-5.13 2.386-4.994 5.238l13.2 277.042c1.22 25.64 22.28 45.72 47.94 45.72h242.98c25.66 0 46.72-20.08 47.94-45.72l13.2-277.042c.136-2.852-2.139-5.238-4.994-5.238zm241.636 40c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16zm-80 0c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16zm-80 0c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16z"/>
                                                </g>
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td class="text-center" colspan="6">Vous n'avez pas encore créer d'articles</td>
                        </tr>
                    {% endif %}
                    </tbody>
                    {% if posts.items|length > 10 %}
                        <tfoot>
                            <tr>
                                <td>
                                    <div class="nav-pagination">
                                        {{ knp_pagination_render(posts) }}
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/contributor/posts/edit.html.twig
{% extends 'contributor/partials/base.html.twig' %}

{% block title %}Editer la veille {% endblock %}

{% block body %}
    <div class="container frame mb-3">
        <h1>Editer votre veille </h1>
    </div>
    <div class="container frame">
        {{ form_start(form) }}
        <div class="row">
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_errors(form.title) }}
                {{ form_label(form.title) }}
                {{ form_widget(form.title) }}
            </div>
            <div class="col-md-12 col-lg-6 mb-3">
                {{ form_errors(form.slug) }}
                {{ form_label(form.slug) }}
                {{ form_widget(form.slug) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 mb-3">
                {% if post.urlImage is not null %}
                    <img src="{{ vich_uploader_asset( post, 'imageFile') }}" alt="image de l'article de veille" class="img-fluid">
                {% else %}
                    Cet article n'a pas encore d'image.
                {% endif %}
            </div>
            <div class="col-sm-12 col-md-6 mb-3">
                {{ form_errors(form.imageFile) }}
                {{ form_label(form.imageFile) }}
                {{ form_widget(form.imageFile) }}
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                {{ form_errors(form.refDescription) }}
                {{ form_label(form.refDescription) }}
                {{ form_widget(form.refDescription) }}
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                {{ form_errors(form.excerpt) }}
                {{ form_label(form.excerpt) }}
                {{ form_widget(form.excerpt) }}
            </div>
            <div class="col-12 mb-3">
                {{ form_errors(form.content) }}
                {{ form_label(form.content) }}
                {{ form_widget(form.content) }}
            </div>
        </div>
        <div class="row">
            <button class="btn btn-primary" type="submit">Enregistrer les modifications</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}