src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

//use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Class Comment.
 *
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected ?int $id;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $content;

    /**
     * @ORM\Column(type="string", length=180)
     * @Assert\NotBlank
     */
    protected ?string $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $commented_at;

    /**
     * @ORM\Column(type="boolean")
     */
    protected bool $approval;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     */
    protected ?User $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="comments")
     */
    protected ?Post $post;

    //getters and setters
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCommentedAt(): ?\DateTimeInterface
    {
        return $this->commented_at;
    }

    public function setCommentedAt(\DateTimeInterface $commented_at): self
    {
        $this->commented_at = $commented_at;

        return $this;
    }

    public function getApproval(): ?bool
    {
        return $this->approval;
    }

    public function setApproval(bool $approval): self
    {
        $this->approval = $approval;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $user): self
    {
        $this->author = $user;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Class Post.
 *
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une autre veille posséde déjà ce titre, merci de le modifier"
 * )
 * @UniqueEntity(
 *     fields={"slug"},
 *     message="Ce slug est déjà utilisé pour une autre veille."
 * )
 * @Vich\Uploadable()
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected ?int $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected ?string $title;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected ?string $slug;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/jpg", "image/png"}
     * )
     * @Vich\UploadableField(mapping="post_image", fileNameProperty="url_image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected ?string $url_image;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $excerpt;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $content;

    /**
     * @ORM\Column(type="text")
     */
    protected ?string $ref_description;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $post_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $post_modified_at;

    /**
     * @ORM\Column(type="boolean")
     */
    protected bool $validatedAt;

    /**
     * @ORM\Column(type="integer")
     */
    protected int $viewsCount = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     */
    protected ?User $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="post")
     */
    private $favorites;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="posts")
     */
    protected Collection $tag;

    public function __construct()
    {
        $this->tag = new ArrayCollection();
    }

    //getters and setters
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->updatedAt = new \DateTime('now');
        }

//        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(?string $urlImage): self
    {
        $this->url_image = $urlImage;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->excerpt;
    }

    public function setExcerpt(string $excerpt): self
    {
        $this->excerpt = $excerpt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getRefDescription(): ?string
    {
        return $this->ref_description;
    }

    public function setRefDescription(string $ref_description): self
    {
        $this->ref_description = $ref_description;

        return $this;
    }

    public function getPostCreatedAt(): ?\DateTimeInterface
    {
        return $this->post_created_at;
    }

    public function setPostCreatedAt(\DateTimeInterface $post_created_at): self
    {
        $this->post_created_at = $post_created_at;

        return $this;
    }

    public function getPostModifiedAt(): ?\DateTimeInterface
    {
        return $this->post_modified_at;
    }

    public function setPostModifiedAt(?\DateTimeInterface $post_modified_at): self
    {
        $this->post_modified_at = $post_modified_at;

        return $this;
    }

    public function isValidatedAt(): ?bool
    {
        return $this->validatedAt;
    }

    public function setValidatedAt(bool $validatedAt): self
    {
        $this->validatedAt = $validatedAt;

        return $this;
    }

    public function getViewsCount(): ?int
    {
        return $this->viewsCount;
    }

    public function setViewsCount(int $viewsCount): self
    {
        $this->viewsCount = $viewsCount;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $user): self
    {
        $this->author = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): Comment
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): Post
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setPost($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): Post
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getPost() === $this) {
                $favorite->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
            $tag->addPost($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
            $tag->removePost($this);
        }

        return $this;
    }

//    public function getTag(): ?Tag
//    {
//        return $this->tag;
//    }
//
//    public function setTag(?Tag $tag): self
//    {
//        $this->tag = $tag;
//
//        return $this;
//    }

//    public function getUser(): ?User
//    {
//        return $this->user;
//    }
//
//    public function setUser(?User $user): self
//    {
//        $this->user = $user;
//
//        // set (or unset) the owning side of the relation if necessary
//        $newAvatar = null === $user ? null : $this;
//        if ($user->getAvatar() !== $newAvatar) {
//            $user->setAvatar($newAvatar);
//        }
//
//        return $this;
//    }

    public function __toString()
    {
        return (string) $this->getUrlImage();
    }

    /**
     * To initialize slug on persist or update.
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(): void
    {
        $slugify = new Slugify();
        $this->slug = $slugify->slugify($this->title);
//        if(empty($this->slug)){
//            $slugify = new Slugify();
//            $this->slug = $slugify->slugify($this->title);
//        }
//        if(!empty($this->slug)){
//            $slugify = new Slugify();
//            $this->slug = $slugify->slugify($this->title);
//        }
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\Comments\CreateCommentType;
use App\Repository\FavoriteRepository;
use App\Repository\PostRepository;
use App\Services\TagStatsManager;
use App\Services\UserStatsManager;
use Doctrine\ORM\ORMException;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    private PostRepository $postRepository;
    private RequestStack $request;
    private TagStatsManager $tagStatsManager;
    private UserStatsManager $userStatsManager;
    private ManagerRegistry $doctrine;

    public function __construct(
        RequestStack $request,
        PostRepository $postRepository,
        TagStatsManager $tagStatsManager,
        UserStatsManager $userStatsManager,
        ManagerRegistry $managerRegistry
    ) {
        $this->postRepository = $postRepository;
        $this->request = $request;
        $this->tagStatsManager = $tagStatsManager;
        $this->userStatsManager = $userStatsManager;
        $this->doctrine = $managerRegistry;
    }

    /**
     * @param PaginatorInterface $paginator
     * @return Response
     * @throws \Exception
     * @Route("/veilles", name="veilles_index")
     */
    public function index(PaginatorInterface $paginator): Response
    {
        $elementPerPage = 6;
        $posts = $paginator->paginate(
            $this->postRepository->findAllRecent(),
            $this->request->getCurrentRequest()->query->getInt('page', 1),
            $elementPerPage
        );
        $pageCount = ceil($posts->getTotalItemCount() / $elementPerPage);

        return $this->render('blog/index.html.twig', [
            'posts' => $posts,
            'pageCount' => $pageCount
        ]);
    }

    /**
     * @param $slug
     * @param Request $request
     * @param FavoriteRepository $favoriteRepository
     * @return Response
     * @throws ORMException
     * @Route("/veilles/{slug}", name="veilles_show")
     */
    public function show(
        $slug,
        Request $request,
        FavoriteRepository $favoriteRepository
    ): Response {
        $entityManager = $this->doctrine->getManager();

        //update post view count
        $post = $this->postRepository->findBy(['slug' => $slug]);
        $modifyPost = $post[0];
        $modifyPost->setViewsCount($modifyPost->getViewsCount() + 1);
        $entityManager->flush();

        //update tag view count
        //vérifier si le post a un ou plusieurs tags
        //si c'est le cas lancer le tagStatsManager
        $postTags = $post[0]->getTag()->toArray();
        if (!empty($postTags)) {
            $this->tagStatsManager->updateTagsStats($postTags, "view-count");
        }

        $favorite = false;
        //update user stats
        if ($this->getUser() !== null) {
            $this->userStatsManager->updateTagsAndPostCounter($this->getUser(), $post);
            if ($favoriteRepository->
                findFavoriteWithUserIdAndPostId($this->getUser()->getId(), $post[0]->getId()) !== null
            ) {
                $favorite = true;
            }
        }

        $comments = $post[0]->getComments()->toArray();

        //dd($comments);

        $form = $this->createForm(CreateCommentType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //$commentFromForm = $form->getData();
            $comment = new Comment();
            //dd($comment);
            if ($this->getUser()) {
                $comment->setAuthor($this->getUser());
                $comment->setEmail($this->getUser()->getEmail());
            } else {
                $comment->setAuthor(null);
                $comment->setEmail($form->get('email')->getData());
            }
            $comment->setPost($post[0]);
            $comment->setCommentedAt(new \DateTime());
            $comment->setApproval(false);
            $comment->setContent($form->get('content')->getData());

            $entityManager->persist($comment);
            $entityManager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte !"
            );

            return $this->redirectToRoute('veilles_show', ['slug' => $slug]);
        }

        return $this->render('blog/show.html.twig', [
            'post' => $post[0],
            'comments' => $comments,
            'form' => $form->createView(),
            'favorite' => $favorite,
        ]);
    }
}

templates/blog/index.html.twig
{%  extends 'site/partials/base.html.twig' %}

{% block title %}Veilles - Front2Back{% endblock %}

{% block body %}
    <h1>Les veilles</h1>

    <div class="container">
        {% for post in posts %}
            <div class="row mt-5 mb-5 horizontal-card">
                <div class="col-sm-12 col-md-4 card-image">
                    {% if post.urlImage is not null %}
                        <img src="{{ vich_uploader_asset(post, 'imageFile')}}" alt="image de la veille">
                    {% else %}
                        Cet article n'a pas encore d'image
                    {% endif %}
                </div>
                <div class="col-sm-12 col-md-8 card-content">
                    <h3>{{ post.title }}</h3>
                    <p>
                        {{ post.excerpt }}
                    </p>
                    <a class="btn btn-primary" href="{{ path('veilles_show', {'slug': post.slug}) }}">Lire la suite</a>
                </div>
            </div>
        {% endfor %}

{#        changer cette condition, regarder dans le paginator#}
        {% if pageCount > 1 %}
            <div class="row mt-5 mb-5 horizontal-card">
                <div class="col-12">
                    <div class="nav-pagination">
                        {{ knp_pagination_render(posts) }}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/blog/show.html.twig
{% extends 'site/partials/base.html.twig' %}

{% block title %}{{ post.title}} - Front2Back{% endblock %}

{% block stylesheets %}
    {#{{ encore_entry_link_tags('app') }}#}
    {{ encore_entry_link_tags('site') }}
    {{ encore_entry_link_tags('blog') }}
{% endblock %}

{% block body %}
    <div class="container glass-frame mb-5">
        {% if post.urlImage is not null %}
            <img class="img-post" src="{{ vich_uploader_asset(post, 'imageFile')}}" alt="image de la veille">
        {% else %}
            Cet article n'a pas encore d'image
        {% endif %}
    </div>

    <div class="container glass-frame" id="post-content" data-id="{{ post.id }}">
        <h1>{{ post.title }}</h1>
        {% if favorite == false %}
            <span id="heartBtnFavorite" class="heart-container">
                <i class="like-button far fa-heart">
                    <i class="like-button__filled far fa-heart"></i>
                </i>
            </span>
        {% else %}
            <span id="heartBtnFavorite" class="heart-container">
                <i class="like-button__favorite fas fa-heart"></i>
            </span>
        {% endif %}
{#        {{ dump(post.tag) }}#}
        {% set tags = post.tag %}
        {% if tags is not empty %}
            <p>
            Tag: <br/>
            {% for tag in tags %}
                <a href="{{ path('tag_show', {'slug': tag.slug}) }}">{{ tag.name }}</a>
            {% endfor %}
            </p>
        {% endif %}
        <p>Auteur de la veille: {{ post.author.firstname }}</p>
        <p>Veille posté le {{ post.postCreatedAt | date("d/m/Y H:i:s") }}</p>
        <p>{{ post.content }}</p>
    </div>

    <div class="container glass-frame mt-5">
        <h2 class="text-center">Poster un commentaire</h2>
        {{ form_start(form) }}
        {% if app.user is null %}
{#            {{ dump(app.user) }}#}
{#            {{ form_row(form.email) }}#}
            <div class="row">
                <div class="col-12">
                {{ form_errors(form.email) }}
                {{ form_label(form.email) }}
                {{ form_widget(form.email) }}
                </div>
            </div>
        {% endif %}
        <div class="row mt-3">
            <div class="col-12">
                {{ form_errors(form.content) }}
                {{ form_label(form.content) }}
                {{ form_widget(form.content) }}
            </div>
        </div>
        <button class="btn btn-primary mt-3" type="submit">Commenter</button>
        {{ form_end(form) }}
    </div>

    <div class="container glass-frame mt-5">
        <h2 class="text-center mb-3">Commentaires</h2>
        {% if comments is empty %}
            <p class="text-center">Aucuns commentaires pour l'instant sur cet article</p>
        {% else %}
            {% for comment in comments %}
                {% if comment.approval == true %}
                    <div class="container glass-frame mb-3">
                        <p>Commentaire posté le {{ comment.commentedAt | date("d/m/Y H:i:s") }}</p>
                        <p>L'auteur du commentaire: {{ comment.author.firstname }}</p>
                        <p>{{ comment.content }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('site') }}
    {{ encore_entry_script_tags('blog') }}
{% endblock %}